#!/usr/bin/bash -xe
# Copyright 2017 Petr Horacek
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pushd /etc/sysconfig/network-scripts

for file in `ls | grep "^\(ifup\|ifdown\).*$" | grep -v "^.*backup$"`; do
    cp ${file} ${file}.backup
    new_header="#!/usr/bin/bash -x\nPS4='\$(date \"+  %s.%N \${LINENO} ${file} \")'"
    sed -i "1s&.*&${new_header}&" ${file}
done

popd
